/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WomenRouteImport } from './routes/women'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as MenRouteImport } from './routes/men'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AccountAdminRouteImport } from './routes/account.admin'
import { Route as CGenderSlugRouteImport } from './routes/c.$gender.$slug'

const WomenRoute = WomenRouteImport.update({
  id: '/women',
  path: '/women',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const MenRoute = MenRouteImport.update({
  id: '/men',
  path: '/men',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AccountAdminRoute = AccountAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AccountRoute,
} as any)
const CGenderSlugRoute = CGenderSlugRouteImport.update({
  id: '/c/$gender/$slug',
  path: '/c/$gender/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/men': typeof MenRoute
  '/order-success': typeof OrderSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/women': typeof WomenRoute
  '/account/admin': typeof AccountAdminRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/p/$slug': typeof PSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/c/$gender/$slug': typeof CGenderSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/men': typeof MenRoute
  '/order-success': typeof OrderSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/women': typeof WomenRoute
  '/account/admin': typeof AccountAdminRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/p/$slug': typeof PSlugRoute
  '/admin': typeof AdminIndexRoute
  '/c/$gender/$slug': typeof CGenderSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/men': typeof MenRoute
  '/order-success': typeof OrderSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/women': typeof WomenRoute
  '/account/admin': typeof AccountAdminRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/p/$slug': typeof PSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/c/$gender/$slug': typeof CGenderSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/login'
    | '/men'
    | '/order-success'
    | '/privacy'
    | '/refund'
    | '/shipping'
    | '/shop'
    | '/signup'
    | '/terms'
    | '/track-order'
    | '/wishlist'
    | '/women'
    | '/account/admin'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/products'
    | '/p/$slug'
    | '/admin/'
    | '/c/$gender/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/login'
    | '/men'
    | '/order-success'
    | '/privacy'
    | '/refund'
    | '/shipping'
    | '/shop'
    | '/signup'
    | '/terms'
    | '/track-order'
    | '/wishlist'
    | '/women'
    | '/account/admin'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/products'
    | '/p/$slug'
    | '/admin'
    | '/c/$gender/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/login'
    | '/men'
    | '/order-success'
    | '/privacy'
    | '/refund'
    | '/shipping'
    | '/shop'
    | '/signup'
    | '/terms'
    | '/track-order'
    | '/wishlist'
    | '/women'
    | '/account/admin'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/products'
    | '/p/$slug'
    | '/admin/'
    | '/c/$gender/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  MenRoute: typeof MenRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  ShippingRoute: typeof ShippingRoute
  ShopRoute: typeof ShopRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  TrackOrderRoute: typeof TrackOrderRoute
  WishlistRoute: typeof WishlistRoute
  WomenRoute: typeof WomenRoute
  PSlugRoute: typeof PSlugRoute
  CGenderSlugRoute: typeof CGenderSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/women': {
      id: '/women'
      path: '/women'
      fullPath: '/women'
      preLoaderRoute: typeof WomenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/men': {
      id: '/men'
      path: '/men'
      fullPath: '/men'
      preLoaderRoute: typeof MenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/admin': {
      id: '/account/admin'
      path: '/admin'
      fullPath: '/account/admin'
      preLoaderRoute: typeof AccountAdminRouteImport
      parentRoute: typeof AccountRoute
    }
    '/c/$gender/$slug': {
      id: '/c/$gender/$slug'
      path: '/c/$gender/$slug'
      fullPath: '/c/$gender/$slug'
      preLoaderRoute: typeof CGenderSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountAdminRoute: typeof AccountAdminRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAdminRoute: AccountAdminRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  MenRoute: MenRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  ShippingRoute: ShippingRoute,
  ShopRoute: ShopRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  TrackOrderRoute: TrackOrderRoute,
  WishlistRoute: WishlistRoute,
  WomenRoute: WomenRoute,
  PSlugRoute: PSlugRoute,
  CGenderSlugRoute: CGenderSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
